### ISSUE TITLE
500 Internal Server Error (Unable to prepare statement)

### ISSUE THREAD

**Issue by iseries** [Flowpack/Flowpack.SimpleSearch#20]
**description**
I got an internal server error after installing the flowpack/simplesearch-contentrepositoryadaptor and trying to add the Search Form into the Page. I wanted to open this issue in flowpack/simplesearch-contentrepositoryadaptor at first but the error message points to the Flowpack.SimpleSearch package.

![neoserror](https://user-images.githubusercontent.com/6272363/28359076-620b21dc-6c71-11e7-8277-bb979dd96f1d.gif)

**reproduce**

`php70 composer.phar create-project neos/neos-base-distribution Neos`

- install neos with demo package

```
cd Neos
php70 ../composer.phar require flowpack/simplesearch-contentrepositoryadaptor --no-update 
php70 ../composer.phar update --no-dev
php70 flow flow:cache:flush
```

- login to the neos backend
- add "Search" NodeType (Flowpack.SimpleSearch.ContentRepositoryAdaptor:Search) into the main content collection.

error appears:

```
Server communication error: 500 Internal Server Error
Warning: SQLite3::query(): Unable to prepare statement: 1, no such column: __identifier in /usr/www/users/c0000053/Neos/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Flowpack_SimpleSearch_Domain_Service_SqLiteIndex.php line 193

Exception Code1Exception TypeNeos\Flow\Error\ExceptionLog Reference20170719103616095e07Thrown in FilePackages/Framework/Neos.Flow/Classes/Error/ErrorHandler.phpLine81
```

**my setup**

Neos.Neos 3.1.3
Neos.Flow 4.1.3
Flowpack.SimpleSearch 2.0.0
Flowpack.SimpleSearch.ContentRepositoryAdaptor 2.0.1

**Comment by iseries** [comment]
ok after reading the error careful i realized that i have to doctrine:update (maybe this should noticed in the package readme).. however -> now i have another (old) problem.

If i  move text elements (for example) via drag and drop in the structure three i got:
```
Warning: SQLite3::query(): Unable to prepare statement: 5, database is locked in /usr/www/users/c0000053/Neos/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Flowpack_SimpleSearch_Domain_Service_SqLiteIndex.php line 278

Exception Code1Exception TypeNeos\Flow\Error\ExceptionLog Reference20170719142011548825Thrown in FilePackages/Framework/Neos.Flow/Classes/Error/ErrorHandler.phpLine81
```
this happens not every time but i can reproduce it by moving 2 text nodes very fast behind each other.

**Comment by kitsunet** [comment]
Probalby a concurrency issue :/

**Comment by kdambekalns** [comment]
No `doctrine:migrate` involved here, the search is based on SQLite (as the error message shows). My guess: no index exists, did you run `nodeindex:build` at least once?

**Comment by iseries** [comment]
Cant't tell. Had this problem in a neos instance i do not serve and support anymore. Sorry.
