### ISSUE TITLE
Missing required constructor argument $storageFolder in class Flowpack\SimpleSearch\Domain\Service\SqLiteIndex.

### ISSUE THREAD

**Issue by mirkokaufmann** [Flowpack/Flowpack.SimpleSearch#8]
While using Flow 3.1.0 and Neos 2.1.3 the following error occures:

Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.

Type: TYPO3\Flow\Object\Exception\UnresolvedDependenciesException
Code: 1296143788
File: Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Flowpack_SimpleSearch_Domain_Service_SqLiteIndex.php
Line: 322

Exception #1296143788 in line 48 of Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Flowpack_SimpleSearch_Factory_IndexFactory.php: Missing required constructor argument $storageFolder in class Flowpack\SimpleSearch\Domain\Service\SqLiteIndex.

**Comment by Sebobo** [comment]
Fixed it for me now by modifying the constructor and adding a setter for `storageFolder`:

    /**
	 * @param string $indexName
	 */
	public function __construct($indexName) {
		$this->indexName = $indexName;
	}

	/**
	 * @param string $storageFolder
	 */
	public function setStorageFolder($storageFolder)
	{
		$this->storageFolder = $storageFolder;
	}

**Comment by kitsunet** [comment]
Alright, fixed this by adapting the constructor and objects configuration.
